### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Renanuya** [Renanuya/contrast-equalisation-python#1]
- [x] <img width="571" alt="image" src="https://github.com/Renanuya/contrast-equalisation-python/assets/69991160/0ab63970-0e7b-482e-8ab8-177b29927384"> Tabloların doğru şekilde koyulduğu kontrol edilecek.
- [x] ipynb dosyası oluşturulacak.
- [x] eşitlenmiş data yeni bir excel dosyası olarak kayıt edilecek.
